version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/annihilatorrrr/RamEater"

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "rustfmt"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "black"

[[transformers]]
name = "yapf"